resources:
   - name: source-code
     type: git
     icon: github
     source:
        uri: https://github.com/DipayanP007/Jenkins-Concourse-maven-project.git
        branch: master

jobs:
   - name: maven-goal
     plan:
        - get: source-code
        - task: maven-exec
          config:
             platform: linux
             image_resources:
                 type: docker-image
                 source:
                    repository: ubuntu
             
             inputs:
                - name: source-code
             run:
                path: find
                args: [.]